# Generated by Django 2.2.6 on 2019-10-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191011_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author_name',
        ),
    ]
